theme = "dracula"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["version-control", "selections", "total-line-numbers", "position"]

